# I/O configuration

simulation_name: Takahashi 2019
simulation_description: |
  full-sky lensing maps and halos in lightcones
  lightcones cover sky fraction of fsky=1/48, or 680 deg2,
  480 realisations at z = 0.1, 0.3, 0.5, 0.7


inputfile:
    filename_sets: ['000','001','002','003','004','005','006','007','008','009','010','011','012','013','014','015','016','017','018','019','020','021','022','023','024','025','026','027','028','029','030','031','032','033','034','035','036','037','038','039','040','041','042','043','044','045','046','047','048','049','050','051','052', '053']
    halocat_filename_base: /global/cfs/cdirs/lsst/groups/CL/takahashi_sims/catalogs/skyhalo_nres12r
    halocat_filename_suffix: .halo
    shear_filename_base: /global/cfs/cdirs/lsst/groups/CL/takahashi_sims/allskymaps/allskymap_nres12r
    shear_filename_suffix: .zs18.mag.dat
    ## shear_filename_suffix stil needs to be changed. s18 corresonds to the source redshift 0.508 to 0.574



# Jackknife measurement configuration
nsky: [32, 64, 128]
run_treecorr: True
use_randoms: False
low_memory_flag: True
njk_patch:
  32:  50
  64:  50
  128: 50
outputpath: measurements/
#nsky: 4
#nsky: 8

tree_corr_angle:
    min: 0.1
    max: 100.0
    nbins: 50


source_redshifts: 
    min: 0.508
    max: 0.574

source_mass: 
    min: 14.0
    max: 15.5